name: R-hello-world

on: push

jobs:
  R-CMD-check:
    runs-on: ununtu-latest
    
    steps:
      - uses: r-lib/actions/setup-r@v1
      
      - name: Say hello
        run: |
          cat("Hello world!")
        shell: Rscript {0}
