name: R-hello-world

on: [push]

jobs:
  say-hello-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: r-lib/actions/setup-r@v2
      
      - name: Say hello
        run: |
          cat("Hello world!")
        shell: Rscript {0}
